### ISSUE TITLE
need to set selinux booleans to allow nginx wrapper to work

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-solr-onesearch#1]
we do this stuff in the application roles, so this seems like a good place for it.  adapted from d7 role (nginx uses the same booleans as apache):
```
- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
    - httpd_can_network_connect
```
